# Generated by Django 5.0.2 on 2024-03-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='service'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(max_length=255, upload_to='doctor'),
        ),
    ]
