# Generated by Django 5.0.2 on 2024-03-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_service_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='class_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
