# Generated by Django 5.0.2 on 2024-03-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_service_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='class_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
