# Generated by Django 5.0.2 on 2024-03-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_date_time_alter_appointment_app_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='comment',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
