# Generated by Django 5.0.2 on 2024-03-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_appointment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='comment',
        ),
    ]
