# Generated by Django 5.0.2 on 2024-03-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_remove_appointment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
